### ISSUE TITLE
Laag contrast

### ISSUE THREAD

**Issue by vasilisvg** [FMJansen/inclusief.design#47]
De richtlijnen van de WCAG zijn natuurijk geen wetten. Maar vaak wel heel aardige uitganspunten. Wit op oranje is, vreemd genoeg, een wat problematische combinatie. Maar vooral deze `opacity` zorgt er voor dat het contrast voor, bijvoorbeeld _mensen van rond de vijftig die hun leesbril ’s ochtends niet op willen zetten_ te laag wordt. De header en de navigatie worden erg moeilijk leesbaar. 

![Screenshot van de lage contrastwaarde](https://ndoe.nl/screen/1613717768-185820929.png)

https://github.com/FMJansen/inclusief.design/blob/3785952c5551b738b7095987e8f6e32eebb6321a/src/scss/base.scss#L66

**Comment by vasilisvg** [comment]
Er zijn meerdere tooltjes om contrast te checken. Bijvoorbeeld:

- [Contrast (Mac app)](https://usecontrast.com/)
- [Contrast Ratio (website)](https://contrast-ratio.com/)

**Comment by FMJansen** [comment]
Hey @vasilisvg! Thanks voor de issue :) Ik had ’m zo gedaan dat de opacity verdwijnt on hover en daardoor de contrast ratio nog wel AA is, maar misschien inderdaad beter om dat weg te halen zodat het altijd beter leesbaar is. Ik zal sowieso nog even naar de kleur kijken om alles naar AAA te tillen.

Nog wel een vraag; #e20003 hoort eigenlijk #d93920 te zijn; had jij zelf de kleur aangepast op dit screenshot of gaat er iets anders mis? 🤔

**Comment by vasilisvg** [comment]
Kleuren en computers en browsers! Wat een bizarre combi. In Firefox is het bij mij #e20003 en in Chrome en Safari is het op deze Mac laptop #ce251a. 
Level AAA en toch gewoon mooi is inderdaad gewoon het allercoolst. En volgens mij is dat prima te doen.

**Comment by FMJansen** [comment]
Heel bizar 😱 Dat zijn dezelfde browsers als waar ik in werk op macOS. Ik heb nu twee fixes gedaan waardoor het in theorie nu AAA moet zijn. Maar een écht mooie kleur zal ik nog een keer moeten vinden.
